### ISSUE TITLE
页面状态无法保存

### ISSUE THREAD

**Issue by Rennzh** [lensh/vue-qq#12]
比如说：我在消息列表将列表滚动到底部（先把窗口高度调小），随意点击列表中的一个item，进入聊天详细页面，点击返回时，列表会自动滚动回顶端。
其他有列表的页面都有这种情况。

**Comment by lensh** [comment]
您好，现在已经修复了这个bug，具体如何修复的可以参考最新的commit，非常感谢您的issue~~

**Comment by lensh** [comment]
您好，现在已经修复了这个bug，具体如何修复的可以参考最新的commit，非常感谢您的issue~~

**Comment by Rennzh** [comment]
嗯，我刚刚看了下，你现在是记录了当前页面列表的滚动位置吧，因为返回时的列表有时会出现明显的滚动行为。

**Comment by lensh** [comment]
是的，记录滚动的位置。虽有不足，但目前只能想到这个方法了，希望有更好的解决办法~~
